# Generated by Django 3.0.5 on 2020-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Название фильма', max_length=200)),
                ('description', models.TextField()),
                ('rate', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
